---
# tasks file for hzn-mgmt-hub

- name: Ensure pip is installed
  ansible.builtin.apt:
    state: present
    name: python3-pip
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: Install dependencies
  ansible.builtin.pip:
    state: present
    name: python-dotenv

# Copy the environment file to the remote system (if it exists).
- name: Copy agent install to destination
  ansible.builtin.copy:
    decrypt: true
    mode: '0644'
    src: '{{ agent_install }}'
    dest: '{{ agent_install }}'
  when: agent_install is defined and agent_install != None

- name: Copy administrator environment to destination
  ansible.builtin.copy:
    decrypt: true
    mode: '0600'
    src: '{{ administrator_env }}'
    dest: '{{ administrator_env }}'
  when: administrator_env is defined and administrator_env != None

- name: Copy management hub script to destination
  ansible.builtin.copy:
    mode: '0755'
    src: deploy-mgmt-hub.sh
    dest: deploy-mgmt-hub.sh

# Generate an agent-install.cfg file from environment and YAML variables.
- name: Generate environment for install
  load_env_config:
    ansible_facts: "{{ ansible_facts }}"
    mgmt_hub: '{{ hzn_mgmt_hub | default({}) }}'
    env_file: '{{ administrator_env }}'
    agent_install: '{{ agent_install }}'
  register: pre_install_config

# Write the agent-install.cfg file to disk.
- name: Write agent-install.cfg to disk.
  ansible.builtin.copy:
    mode: '0644'
    content: "{{ pre_install_config.agent_install }}"
    dest: agent-install.cfg

- name: Write administrator.env to disk.
  ansible.builtin.copy:
    mode: '0600'
    content: "{{ pre_install_config.administrator_env }}"
    dest: administrator.env

- name: Install or uninstall the management hub
  import_tasks: install.yml
  when: install or uninstall

- name: Check for facts on remote
  stat:
    path: 'mgmt_hub_configuration.yml'
  register: mgmt_hub_stat_result

- name: Move config from install
  ansible.builtin.set_fact:
    hzn_mgmt_hub: '{{ install_config.hzn_mgmt_hub }}'
  when: install
 
- name: Move config from preinstall
  ansible.builtin.set_fact:
    hzn_mgmt_hub: '{{ pre_install_config.hzn_mgmt_hub }}'
  when: not install and hzn_mgmt_hub is undefined and not mgmt_hub_stat_result.stat.exists

# Load the facts from the active installation. We need this information to control users and orgs.
# It should be coming from an ansible vault, however we can try to load it from the remote system.
- name: Try to load installation facts
  block:
  - name: Slurp from remote
    ansible.builtin.slurp:
      src: 'mgmt_hub_configuration.yml'
    register: hzn_mgmt_hub_slurped
  - name: Set fact
    ansible.builtin.set_fact:
      hzn_mgmt_hub: '{{ hzn_mgmt_hub_slurped.content | b64decode | from_yaml }}'
  when: not uninstall and hzn_mgmt_hub is undefined

- name: Upgrade the management hub
  import_tasks: upgrade.yml
  when: upgrade

- name: Run user and group management
  import_tasks: user_mgmt.yml
  when: not uninstall and exchange_config is defined
